import { 
    TOGGLE_LOGIN_SIGNUP_BTN, TOGGLE_INPUT_FOCUS, TOGGLE_LOGIN_INPUT_FOCUS, TOGGLE_SHOW_FORM, SET_LOGIN_MSG, TOGGLE_LET_USER_REMEMBER_ME, SET_IS_LOGGED_IN_USER, 
        SET_USERNAME_INPUT, SET_PASSWORD_INPUT, SET_EMAIL_INPUT, SET_AGE_INPUT, SET_EMAIL_OR_USERNAME_LOGIN_INPUT, SET_PASSWORD_LOGIN_INPUT, INCREMENT_INCORRECT_LOGIN_ATTEMPT,
        TOGGLE_PASSWORD_SHOW_CLICK, TOGGLE_LOGIN_PASSWORD_SHOW_CLICK, TOGGLE_PARENT_CONFIRM, RESET_INCORRECT_LOGIN_ATTEMPT, SET_ALL_USERNAMES,
         SET_ALL_EMAILS, TOGGLE_SUBMIT_INPUT_DATA, SET_CURRENT_USER, SET_NON_GOOGLE_IMG_URL             
} from 'redux/logInOutGoogle/logInOutGoogleSlice';

export {
        TOGGLE_LOGIN_SIGNUP_BTN, TOGGLE_INPUT_FOCUS, TOGGLE_LOGIN_INPUT_FOCUS, TOGGLE_SHOW_FORM, SET_LOGIN_MSG, TOGGLE_LET_USER_REMEMBER_ME, SET_IS_LOGGED_IN_USER, 
            SET_USERNAME_INPUT, SET_PASSWORD_INPUT, SET_EMAIL_INPUT, SET_AGE_INPUT, SET_EMAIL_OR_USERNAME_LOGIN_INPUT, SET_PASSWORD_LOGIN_INPUT, INCREMENT_INCORRECT_LOGIN_ATTEMPT,
            TOGGLE_PASSWORD_SHOW_CLICK, TOGGLE_LOGIN_PASSWORD_SHOW_CLICK, TOGGLE_PARENT_CONFIRM, RESET_INCORRECT_LOGIN_ATTEMPT, SET_ALL_USERNAMES,
             SET_ALL_EMAILS, TOGGLE_SUBMIT_INPUT_DATA, SET_CURRENT_USER, SET_NON_GOOGLE_IMG_URL    
};
